services:
  # main service. load local dockerfile
  basestation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/release
    user: astra
    command: bash -c "while true; do sleep 5000; done"
    network_mode: host

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile:ro
      - ../srv:/srv:ro
    network_mode: host

  qgis-server:
    build:
      context: ./qgis-server
      dockerfile: Dockerfile
    volumes:
      - ../osm:/data:ro
    environment:
      - LANG=en_EN.UTF-8
      - QGIS_PROJECT_FILE=/data/utah.qgs
      - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
      - DEBUG=1                  # display env before spawning QGIS Server
    network_mode: host
    restart: unless-stopped
