services:
  # main service. load local dockerfile
  basestation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    user: astra
    command: bash -c "while true; do sleep 5000; done"

  # caddy
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
