services:
  # main service. load local dockerfile
  basestation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/release
      - /var/run/docker.sock:/var/run/docker.sock
    user: astra
    command: bash -c "while true; do sleep 5000; done"
    network_mode: host

  # caddy
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile
    network_mode: host
